// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJ6kZK8mnLirMxDo5aczf45WoMD5qMqKc',
    appId: '1:83990787116:web:eca65083f39973fc7e0d89',
    messagingSenderId: '83990787116',
    projectId: 'gun-gangster-arena-91012185',
    authDomain: 'gun-gangster-arena-91012185.firebaseapp.com',
    databaseURL: 'https://gun-gangster-arena-91012185.firebaseio.com',
    storageBucket: 'gun-gangster-arena-91012185.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8792iujpLpyNRxsD5YH5pk3y54_rA4e4',
    appId: '1:83990787116:android:f3342192295ef6a47e0d89',
    messagingSenderId: '83990787116',
    projectId: 'gun-gangster-arena-91012185',
    databaseURL: 'https://gun-gangster-arena-91012185.firebaseio.com',
    storageBucket: 'gun-gangster-arena-91012185.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7oxYuSELRgsOGmAnrUS63cVE0V5Nuo2Y',
    appId: '1:83990787116:ios:419b298caad28d677e0d89',
    messagingSenderId: '83990787116',
    projectId: 'gun-gangster-arena-91012185',
    databaseURL: 'https://gun-gangster-arena-91012185.firebaseio.com',
    storageBucket: 'gun-gangster-arena-91012185.appspot.com',
    androidClientId: '83990787116-k0bfrkhabdf6u8futf4tkufu4cqi0rfo.apps.googleusercontent.com',
    iosClientId: '83990787116-1sdvqqgi43j5paaubb455athluvu986r.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterImic05',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7oxYuSELRgsOGmAnrUS63cVE0V5Nuo2Y',
    appId: '1:83990787116:ios:244f5eaea07b661f7e0d89',
    messagingSenderId: '83990787116',
    projectId: 'gun-gangster-arena-91012185',
    databaseURL: 'https://gun-gangster-arena-91012185.firebaseio.com',
    storageBucket: 'gun-gangster-arena-91012185.appspot.com',
    androidClientId: '83990787116-k0bfrkhabdf6u8futf4tkufu4cqi0rfo.apps.googleusercontent.com',
    iosClientId: '83990787116-su641m5cj3fah07ekcncdos1jenqgf9i.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterImic05.RunnerTests',
  );
}
